# Generated by Django 5.1.7 on 2025-05-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('full_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='data/photos/')),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('password_hash', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='data/photos/')),
                ('date_of_birth', models.DateField()),
                ('cellphone', models.CharField(max_length=15)),
                ('crmv', models.CharField(max_length=10, unique=True)),
                ('date_crmv', models.DateField()),
                ('consult_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('type_service', models.CharField(choices=[('domicilio', 'Domicílio'), ('clinica', 'Clínica'), ('ambos', 'Domicílio e Clínica')], default='clinica', max_length=20)),
            ],
        ),
    ]
